# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ draft, official ]
  pull_request:
    branches: [ draft, official ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wrc
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check with Python WRC script
      run: |
        wrc ./wca-regulations.md --target=check
        wrc-states wca-states.md --target=check
